//Autogenerated code
namespace Models.Enums
{
    public enum AttachmentStatusEnum
    {
        ///<summary>Prepared</summary>
        Prepared = 1,

        ///<summary>Delivered</summary>
        Delivered = 2,

        ///<summary>Received</summary>
        Received = 3
    }
}