//Autogenerated code
namespace Models.Enums
{
    public enum AttachmentTypeEnum
    {
        ///<summary>Document</summary>
        Document = 1,

        ///<summary>Letter</summary>
        Letter = 2,

        ///<summary>Physical</summary>
        Physical = 3
    }
}