//Autogenerated code
namespace Models.Enums
{
    public enum AuditOperationEnum
    {
        ///<summary></summary>
        INSERT = 1,

        ///<summary></summary>
        UPDATE = 2,

        ///<summary></summary>
        DELETE = 3,

        ///<summary></summary>
        PRINT = 4,

        ///<summary></summary>
        MAIL = 5,

        ///<summary></summary>
        SMS = 6
    }
}