//Autogenerated code
namespace Models.Enums
{
    public enum AuthEntityEnum
    {
        ///<summary>action</summary>
        Action = 1,

        ///<summary>annotation-type</summary>
        AnnotationType = 2,

        ///<summary>attachment-status</summary>
        AttachmentStatus = 3,

        ///<summary>attachment-type</summary>
        AttachmentType = 4,

        ///<summary>audit-domain</summary>
        AuditDomain = 5,

        ///<summary>audit-operation</summary>
        AuditOperation = 6,

        ///<summary>auth-entity</summary>
        AuthEntity = 7,

        ///<summary>auth-permission</summary>
        AuthPermission = 8,

        ///<summary>classification</summary>
        Classification = 9,

        ///<summary>delivery-status</summary>
        DeliveryStatus = 10,

        ///<summary>delivery-type</summary>
        DeliveryType = 11,

        ///<summary>direction-type</summary>
        DirectionType = 12,

        ///<summary>gender</summary>
        Gender = 13,

        ///<summary>help</summary>
        Help = 14,

        ///<summary>importance-level</summary>
        ImportanceLevel = 15,

        ///<summary>incoming-type</summary>
        IncomingType = 16,

        ///<summary>individual-relationship</summary>
        IndividualRelationship = 17,

        ///<summary>job-title</summary>
        JobTitle = 18,

        ///<summary>letter-template</summary>
        LetterTemplate = 19,

        ///<summary>localization</summary>
        Localization = 20,

        ///<summary>menu-item</summary>
        MenuItem = 21,

        ///<summary>nationality</summary>
        Nationality = 22,

        ///<summary>notification-type</summary>
        NotificationType = 23,

        ///<summary>old-transaction</summary>
        OldTransaction = 24,

        ///<summary>organization</summary>
        Organization = 25,

        ///<summary>physical-attachment-type</summary>
        PhysicalAttachmentType = 26,

        ///<summary>recipient-status</summary>
        RecipientStatus = 27,

        ///<summary>required-action</summary>
        RequiredAction = 28,

        ///<summary>role</summary>
        Role = 29,

        ///<summary>system-setting</summary>
        SystemSetting = 30,

        ///<summary>system-setting-category</summary>
        SystemSettingCategory = 31,

        ///<summary>transaction</summary>
        Transaction = 32,

        ///<summary>transaction-basis-type</summary>
        TransactionBasisType = 33,

        ///<summary>transaction-relationship</summary>
        TransactionRelationship = 34,

        ///<summary>transaction-type</summary>
        TransactionType = 35,

        ///<summary>work-place</summary>
        WorkPlace = 36,

        ///<summary>user</summary>
        User = 37,

        ///<summary>individual</summary>
        Individual = 38,

        ///<summary>correspondent</summary>
        Correspondent = 39,

        ///<summary>profile</summary>
        Profile = 40
    }
}