//Autogenerated code
namespace Models.Enums
{
    public enum AuthPermissionEnum
    {
        ///<summary>Delete Action</summary>
        DeleteAction = 1,

        ///<summary>Insert Action</summary>
        InsertAction = 2,

        ///<summary>Update Action</summary>
        UpdateAction = 3,

        ///<summary>Delete AnnotationType</summary>
        DeleteAnnotationType = 4,

        ///<summary>Insert AnnotationType</summary>
        InsertAnnotationType = 5,

        ///<summary>Update AnnotationType</summary>
        UpdateAnnotationType = 6,

        ///<summary>Delete AttachmentStatus</summary>
        DeleteAttachmentStatus = 7,

        ///<summary>Insert AttachmentStatus</summary>
        InsertAttachmentStatus = 8,

        ///<summary>Update AttachmentStatus</summary>
        UpdateAttachmentStatus = 9,

        ///<summary>Delete AttachmentType</summary>
        DeleteAttachmentType = 10,

        ///<summary>Insert AttachmentType</summary>
        InsertAttachmentType = 11,

        ///<summary>Update AttachmentType</summary>
        UpdateAttachmentType = 12,

        ///<summary>Delete AuditDomain</summary>
        DeleteAuditDomain = 13,

        ///<summary>Insert AuditDomain</summary>
        InsertAuditDomain = 14,

        ///<summary>Update AuditDomain</summary>
        UpdateAuditDomain = 15,

        ///<summary>Delete AuditOperation</summary>
        DeleteAuditOperation = 16,

        ///<summary>Insert AuditOperation</summary>
        InsertAuditOperation = 17,

        ///<summary>Update AuditOperation</summary>
        UpdateAuditOperation = 18,

        ///<summary>Delete AuthEntity</summary>
        DeleteAuthEntity = 19,

        ///<summary>Insert AuthEntity</summary>
        InsertAuthEntity = 20,

        ///<summary>Update AuthEntity</summary>
        UpdateAuthEntity = 21,

        ///<summary>Delete AuthPermission</summary>
        DeleteAuthPermission = 22,

        ///<summary>Insert AuthPermission</summary>
        InsertAuthPermission = 23,

        ///<summary>Update AuthPermission</summary>
        UpdateAuthPermission = 24,

        ///<summary>Delete Classification</summary>
        DeleteClassification = 25,

        ///<summary>Insert Classification</summary>
        InsertClassification = 26,

        ///<summary>Update Classification</summary>
        UpdateClassification = 27,

        ///<summary>Delete DeliveryStatus</summary>
        DeleteDeliveryStatus = 28,

        ///<summary>Insert DeliveryStatus</summary>
        InsertDeliveryStatus = 29,

        ///<summary>Update DeliveryStatus</summary>
        UpdateDeliveryStatus = 30,

        ///<summary>Delete DeliveryType</summary>
        DeleteDeliveryType = 31,

        ///<summary>Insert DeliveryType</summary>
        InsertDeliveryType = 32,

        ///<summary>Update DeliveryType</summary>
        UpdateDeliveryType = 33,

        ///<summary>Delete DirectionType</summary>
        DeleteDirectionType = 34,

        ///<summary>Insert DirectionType</summary>
        InsertDirectionType = 35,

        ///<summary>Update DirectionType</summary>
        UpdateDirectionType = 36,

        ///<summary>Delete Gender</summary>
        DeleteGender = 37,

        ///<summary>Insert Gender</summary>
        InsertGender = 38,

        ///<summary>Update Gender</summary>
        UpdateGender = 39,

        ///<summary>Delete Help</summary>
        DeleteHelp = 40,

        ///<summary>Insert Help</summary>
        InsertHelp = 41,

        ///<summary>Update Help</summary>
        UpdateHelp = 42,

        ///<summary>Delete ImportanceLevel</summary>
        DeleteImportanceLevel = 43,

        ///<summary>Insert ImportanceLevel</summary>
        InsertImportanceLevel = 44,

        ///<summary>Update ImportanceLevel</summary>
        UpdateImportanceLevel = 45,

        ///<summary>Delete IncomingType</summary>
        DeleteIncomingType = 46,

        ///<summary>Insert IncomingType</summary>
        InsertIncomingType = 47,

        ///<summary>Update IncomingType</summary>
        UpdateIncomingType = 48,

        ///<summary>Delete IndividualRelationship</summary>
        DeleteIndividualRelationship = 49,

        ///<summary>Insert IndividualRelationship</summary>
        InsertIndividualRelationship = 50,

        ///<summary>Update IndividualRelationship</summary>
        UpdateIndividualRelationship = 51,

        ///<summary>Delete JobTitle</summary>
        DeleteJobTitle = 52,

        ///<summary>Insert JobTitle</summary>
        InsertJobTitle = 53,

        ///<summary>Update JobTitle</summary>
        UpdateJobTitle = 54,

        ///<summary>Delete LetterTemplate</summary>
        DeleteLetterTemplate = 55,

        ///<summary>Insert LetterTemplate</summary>
        InsertLetterTemplate = 56,

        ///<summary>Update LetterTemplate</summary>
        UpdateLetterTemplate = 57,

        ///<summary>Delete Localization</summary>
        DeleteLocalization = 58,

        ///<summary>Insert Localization</summary>
        InsertLocalization = 59,

        ///<summary>Update Localization</summary>
        UpdateLocalization = 60,

        ///<summary>Delete MenuItem</summary>
        DeleteMenuItem = 61,

        ///<summary>Insert MenuItem</summary>
        InsertMenuItem = 62,

        ///<summary>Update MenuItem</summary>
        UpdateMenuItem = 63,

        ///<summary>Delete Nationality</summary>
        DeleteNationality = 64,

        ///<summary>Insert Nationality</summary>
        InsertNationality = 65,

        ///<summary>Update Nationality</summary>
        UpdateNationality = 66,

        ///<summary>Delete NotificationType</summary>
        DeleteNotificationType = 67,

        ///<summary>Insert NotificationType</summary>
        InsertNotificationType = 68,

        ///<summary>Update NotificationType</summary>
        UpdateNotificationType = 69,

        ///<summary>Delete OldTransaction</summary>
        DeleteOldTransaction = 70,

        ///<summary>Insert OldTransaction</summary>
        InsertOldTransaction = 71,

        ///<summary>Update OldTransaction</summary>
        UpdateOldTransaction = 72,

        ///<summary>Delete Organization</summary>
        DeleteOrganization = 73,

        ///<summary>Insert Organization</summary>
        InsertOrganization = 74,

        ///<summary>Update Organization</summary>
        UpdateOrganization = 75,

        ///<summary>Delete PhysicalAttachmentType</summary>
        DeletePhysicalAttachmentType = 76,

        ///<summary>Insert PhysicalAttachmentType</summary>
        InsertPhysicalAttachmentType = 77,

        ///<summary>Update PhysicalAttachmentType</summary>
        UpdatePhysicalAttachmentType = 78,

        ///<summary>Delete RecipientStatus</summary>
        DeleteRecipientStatus = 79,

        ///<summary>Insert RecipientStatus</summary>
        InsertRecipientStatus = 80,

        ///<summary>Update RecipientStatus</summary>
        UpdateRecipientStatus = 81,

        ///<summary>Delete RequiredAction</summary>
        DeleteRequiredAction = 82,

        ///<summary>Insert RequiredAction</summary>
        InsertRequiredAction = 83,

        ///<summary>Update RequiredAction</summary>
        UpdateRequiredAction = 84,

        ///<summary>Delete Role</summary>
        DeleteRole = 85,

        ///<summary>Insert Role</summary>
        InsertRole = 86,

        ///<summary>Update Role</summary>
        UpdateRole = 87,

        ///<summary>Delete SystemSetting</summary>
        DeleteSystemSetting = 88,

        ///<summary>Insert SystemSetting</summary>
        InsertSystemSetting = 89,

        ///<summary>Update SystemSetting</summary>
        UpdateSystemSetting = 90,

        ///<summary>Delete SystemSettingCategory</summary>
        DeleteSystemSettingCategory = 91,

        ///<summary>Insert SystemSettingCategory</summary>
        InsertSystemSettingCategory = 92,

        ///<summary>Update SystemSettingCategory</summary>
        UpdateSystemSettingCategory = 93,

        ///<summary>Delete Transaction</summary>
        DeleteTransaction = 94,

        ///<summary>Insert Transaction</summary>
        InsertTransaction = 95,

        ///<summary>Update Transaction</summary>
        UpdateTransaction = 96,

        ///<summary>Delete TransactionBasisType</summary>
        DeleteTransactionBasisType = 97,

        ///<summary>Insert TransactionBasisType</summary>
        InsertTransactionBasisType = 98,

        ///<summary>Update TransactionBasisType</summary>
        UpdateTransactionBasisType = 99,

        ///<summary>Delete TransactionRelationship</summary>
        DeleteTransactionRelationship = 100,

        ///<summary>Insert TransactionRelationship</summary>
        InsertTransactionRelationship = 101,

        ///<summary>Update TransactionRelationship</summary>
        UpdateTransactionRelationship = 102,

        ///<summary>Delete TransactionType</summary>
        DeleteTransactionType = 103,

        ///<summary>Insert TransactionType</summary>
        InsertTransactionType = 104,

        ///<summary>Update TransactionType</summary>
        UpdateTransactionType = 105,

        ///<summary>Delete WorkPlace</summary>
        DeleteWorkPlace = 106,

        ///<summary>Insert WorkPlace</summary>
        InsertWorkPlace = 107,

        ///<summary>Update WorkPlace</summary>
        UpdateWorkPlace = 108,

        ///<summary>Delete User</summary>
        DeleteUser = 109,

        ///<summary>Insert User</summary>
        InsertUser = 110,

        ///<summary>Update User</summary>
        UpdateUser = 111,

        ///<summary>Delete Individual</summary>
        DeleteIndividual = 112,

        ///<summary>Insert Individual</summary>
        InsertIndividual = 113,

        ///<summary>Update Individual</summary>
        UpdateIndividual = 114,

        ///<summary>Delete Correspondent</summary>
        DeleteCorrespondent = 115,

        ///<summary>Insert Correspondent</summary>
        InsertCorrespondent = 116,

        ///<summary>Update Correspondent</summary>
        UpdateCorrespondent = 117,

        ///<summary>Update Profile</summary>
        UpdateProfile = 118,

        ///<summary>Internal Delegation</summary>
        InternalDelegation = 119,

        ///<summary>Employee Delegation</summary>
        EmployeeDelegation = 120,

        ///<summary>External Delegation Request</summary>
        ExternalDelegationRequest = 121,

        ///<summary>Direct Delegation</summary>
        ExternalDelegationExecute = 122,

        ///<summary>Retrieve Request</summary>
        RetrieveRequest = 123,

        ///<summary>Save With External Delegation</summary>
        SaveWithDelegation = 124,

        ///<summary>Deactivate</summary>
        Save = 125,

        ///<summary>Activate</summary>
        Activate = 126
    }
}