//Autogenerated code
namespace Models.Enums
{
    public enum DirectionTypeEnum
    {
        ///<summary>Organization</summary>
        Organization = 1,

        ///<summary>Employee</summary>
        Employee = 2
    }
}