//Autogenerated code
namespace Models.Enums
{
    public enum SearchTemplateEnum
    {
        ///<summary>Main Information</summary>
        MainInformation = 1,

        ///<summary>Incomming Information</summary>
        IncommingInformation = 2,

        ///<summary>Individual Information</summary>
        IndividualInformation = 3
    }
}