//Autogenerated code
namespace Models.Enums
{
    public enum SystemSettingCategoryEnum
    {
        ///<summary>General</summary>
        General = 1,

        ///<summary>Laserfiche</summary>
        Laserfiche = 2,

        ///<summary>Mail</summary>
        Mail = 3,

        ///<summary>SMS</summary>
        SMS = 4,

        ///<summary>Reports</summary>
        Reports = 5
    }
}