//Autogenerated code
namespace Models.Enums
{
    public enum TransactionTypeEnum
    {
        ///<summary>General Incomming</summary>
        General = 1,

        ///<summary>Internal Decision</summary>
        InternalDecision = 2,

        ///<summary>External Decision</summary>
        ExternalDecision = 3,

        ///<summary>Internal Transaction</summary>
        InternalTransaction = 4,

        ///<summary>Outgoing Transaction</summary>
        OutgoingTransaction = 5,

        ///<summary>Transaction Task</summary>
        TransactionTask = 6,

        ///<summary>Transaction Letter</summary>
        TransactionLetter = 7,
        ///<summary>Transaction Announcement</summary>
        TransactionAnnouncement = 8,

        ///<summary>Transaction Assigbment</summary>
        TransactionAssignment = 10

    }
}