//Autogenerated code
namespace Models.Enums
{
    public enum TransactionSourceEnum
    {
        ///<summary>Current System</summary>
        Current = 1,

        ///<summary>Old System</summary>
        Old = 2
    }
}