//Autogenerated code
namespace Models.Enums
{
    public enum ViewPointEnum
    {
        ///<summary>Draft</summary>
        Draft = 1,

        ///<summary>Department Inbox</summary>
        DepartmentInbox = 2,

        ///<summary>Department Outbox</summary>
        DepartmentOutbox = 3,

        ///<summary>Department Saved</summary>
        DepartmentSaved = 4,

        ///<summary>Department Old Transactions</summary>
        DepartmentOldTransactions = 5,

        ///<summary>Employee Inbox</summary>
        EmployeeInbox = 6,

        ///<summary>Employee Outbox</summary>
        EmployeeOutbox = 7,

        ///<summary>Employee Saved</summary>
        EmployeeSaved = 8,

        ///<summary>Employee Old Transactions</summary>
        EmployeeOldTransactions = 9,

        ///<summary>Follow Up</summary>
        FollowUp = 10,

        ///<summary>Retrieve Requests</summary>
        RetrieveRequests = 11,

        ///<summary>Delivery Sheet</summary>
        DeliverySheet = 12,

        ///<summary>External Delegation Requests</summary>
        ExternalDelegationRequests = 13,

        ///<summary>External Delegation Execute</summary>
        ExternalDelegationExecute = 14
    }
}