import { TemplateRef } from "@angular/core";

export interface ChartDTO {
  view?: number[],
  results?: object[],
  scheme?: object,
  schemeType?: string,
  customColors?: Function | object,
  animations?: boolean,
  rangeFillOpacity?: number,
  yAxis?: boolean,
  xAxis?: boolean,
  legendPosition?: string,
  legendTitle?: string,
  legend?: boolean,
  showYAxisLabel?: boolean,
  showXAxisLabel?: boolean,
  roundDomains?: boolean,
  showGridLines?: boolean,
  yAxisLabel?: string,
  xAxisLabel?: string,
  rotateXAxisTicks?: boolean,
  trimYAxisTicks?: boolean,
  trimXAxisTicks?: boolean,
  maxYAxisTickLength?: number,
  maxXAxisTickLength?: number,
  yAxisTicks?: any[],
  xAxisTicks?: any[],
  yAxisTickFormatting?: Function,
  xAxisTickFormatting?: Function,
  gradient?: boolean,
  autoScale?: boolean,
  timeline?: boolean,
  curve?: Function,
  tooltipDisabled?: boolean,
  activeEntries?: object[],
  tooltipTemplate?: TemplateRef<any>,
  seriesTooltipTemplate?: TemplateRef<any>,
  showRefLabels?: boolean,
  showRefLines?: boolean,
  referenceLines?: object[],
  yScaleMax?: number,
  yScaleMin?: number,
  xScaleMax?: any,
  xScaleMin?: any
}